---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
# elasticsearch.url: http://elasticsearch:9200  #need to try this just in case ........


# elasticsearch.url: http://82.196.10.240:9200

elasticsearch.url: http://127.0.0.1:9200
